name: pager
description: A Paging Library for fetch data both locally or remotely
version: 0.0.2
homepage: https://github.com/donpaul120/pager
repository: https://github.com/donpaul120/pager

environment:
  sdk: ">=2.16.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  diffutil_dart: ^3.0.0
  flutter:
    sdk: flutter
  synchronized: ^3.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  test: ^1.19.5

flutter:
